eureka:
   client:
       register-with-eureka : true
       fetch-registry: true
       service-url:
           defaultZone:  http://localhost:8761/eureka/
      
microservice:
    library-client-service:
              endpoints:
                    endpoint:
                         uri:http://library-client-service/customer   
